[View in Colaboratory](https://colab.research.google.com/github/kintarou/django-starter/blob/master/estimation.ipynb)

In [0]:
import numpy as np
import pandas as pd
import scipy as sp
from scipy import stats
from matplotlib import pyplot as plt
import seaborn as sns
sns.set()
%precision 3
%matplotlib inline

In [34]:
from google.colab import files
uploaded = files.upload()

Saving 3-7-1-fish_length.csv to 3-7-1-fish_length (1).csv


In [49]:
fish=pd.read_csv("3-7-1-fish_length.csv")
fish

length
0  4.352982
1  3.735304
2  5.944617
3  3.798326
4  4.087688
5  5.265985
6  3.272614
7  3.526691
8  4.150083
9  3.736104

In [50]:
mu=sp.mean(fish)
mu

length    4.187039
dtype: float64

In [51]:
sigma_2=sp.var(fish,ddof=1)
sigma_2

length    0.680302
dtype: float64

In [52]:
df=len(fish)-1
df

9

In [53]:
se=sigma/sp.sqrt(len(fish))
se

0.194

In [54]:
interval=stats.t.interval(alpha=0.95,df=df,loc=mu,scale=se)
interval

(array([3.749]), array([4.625]))

In [55]:
t_975=stats.t.ppf(q=0.975,df=df)
t_975

2.262

In [56]:
lower=mu-t_975*se
lower

length    3.749047
dtype: float64

In [57]:
upper=mu+t_975*se
upper

length    4.625032
dtype: float64

In [58]:
se2=(sigma*10)/sp.sqrt(len(fish))
stats.t.interval(alpha=0.95,df=df,loc=mu,scale=se2)

(array([-0.193]), array([8.567]))

In [59]:
df2=(len(fish)*10)-1
se3=sigma/sp.sqrt(len(fish)*10)
stats.t.interval(alpha=0.95,df=df2,loc=mu,scale=se3)

(array([4.066]), array([4.309]))

In [60]:
stats.t.interval(alpha=0.99,df=df,loc=mu,scale=se)

(array([3.558]), array([4.816]))

In [61]:
be_included_array=np.zeros(20000,dtype="bool")
be_included_array

array([False, False, False, ..., False, False, False])

In [62]:
np.random.seed(1)
norm_dist=stats.norm(loc=4,scale=0.8)
for i in range(0,20000):
  sample=norm_dist.rvs(size=10)
  df=len(sample)-1
  mu=sp.mean(sample)
  std=sp.std(sample,ddof=1)
  se=std/sp.sqrt(len(sample))
  interval=stats.t.interval(0.95,df,mu,se)
  if(interval[0]<=4 and interval[1]>=4):
    be_included_array[i]=True
sum(be_included_array)/len(be_included_array)    

0.948